### ISSUE TITLE
LiveLink troubleshoots with ArmorPaint self-Compiled version

### ISSUE THREAD

**Issue by august0815** [PiloeGAO/Blender-ArmorPaintLiveLink#1]
Hi, I am using Linux Mint 19.3, blender 2.82 latest version.
After instilling I had some problems with detecting the path to armorpaint.
1. after build, my armorpaint is somewhere in nowhere, named krom by make, there is no deploy/install in the makefiles.
2. I managed to point to armorpaint, ugly by typing the path directly in to the string.
3. At  line 125 
 #Launch ArmorPaint
            subprocess.Popen([path_exe,path_tmp])
this passes the command  $armorpaint tmp.obj  ?
But armorpaint opens with cub an not with my selected object.
If you wish I send you the snippet code I changed

**Comment by PiloeGAO** [comment]
Hi august0815,

First of all thank you for your feedback and sorry for all the problems you have.

This list countain all the answer for your problems:
1. When you build yourself ArmorPaint, you actually build two things:
- The ArmorPaint Source code from Haxe
- Krom for your OS
Krom is the cross-platform "interpreter" for the compiled ArmorPaint source code.
By default, on start, Krom check in th current directory for "krom.js" and the data directory but the makefiles doesn't copy those files automaticly (and that why you need to parse "..\..\build\krom" at the Krom start).

For an optimum experience, please use the official release from the ArmorPaint website. (https://armorpaint.org/download.html)

2. By doing these tasks you in fact done the same action as describe on the ArmorPaint Github page.

3. The script exports the obj inside of the data directory (this directory is the same from the top).
Then the "Popen" start ArmorPaint, and add the path to the "data/tmp.obj" in the arguments.

I am currently working on a more efficient version of this addon with new functions to improve the user experience.
Don't forget to follow my twitter account to receive all news. (https://twitter.com/LeoDepoix)
