### ISSUE TITLE
It tries to write in the application directory which is read-only

### ISSUE THREAD

**Issue by tobiasBora** [PiloeGAO/Blender-ArmorPaintLiveLink#10]
Hello,

First, thanks for this promising tool. However, I tried to use it in Linux, and the script fails because it tries to save the `tmp.obj` file in the `data` folder of the executable (actually, in my case I created a wrapper so the data folder does not even exist). But this folder is read-only (users are not allowed to modify system programs in linux), so the script fails. Why don't you simply save it to a temporary folder, like `/tmp` on linux, or directly in the project folder? Or it may be a good idea to use directly:

```
import tempfile
# Go to line 318
path_tmp = tempfile.mkstemp(suffix=".obj")[1]
```

-- EDIT --
I just created a PR.

**Comment by PiloeGAO** [comment]
Hi @tobiasBora,

Thank you for your contribution.
