### ISSUE TITLE
APLL on Manjaro LINUX: How to start AP?

### ISSUE THREAD

**Issue by StrandedAlien** [PiloeGAO/Blender-ArmorPaintLiveLink#12]
What am I missing? I don´t know how to start AP from your script. See Screenshots. Please help.
Already solved the issue with the required absolute path... and now this. 2 bad.

Deleted two screenies, were not properly edited. My bad.

Exported and manually setup :
![Screenshot_2021-10-16_19-49-50](https://user-images.githubusercontent.com/89656885/137600436-4ffb4d25-6f15-44e0-a725-8c244cea994d.jpg)

**Comment by StrandedAlien** [comment]
Don´t know how to properly pull request, but found a solution. Should be tested before release. Somebody please try it (also on Win, just in case):
https://github.com/StrandedAlien/Blender-ArmorPaintLiveLink 4 LINUX

**Comment by PiloeGAO** [comment]
Hi @StrandedAlien,

I took a look at your code and it may work.
Unfortunately, the modifications are more quick fixes than real solution.
Also, you are using a self-compiled version of ArmorPaint, so the modifications you have made don't work for the official builds (Which are targetted by the addon).

For your information, you can create pull request by following this documentation: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

Thank you.
