### ISSUE TITLE
Blender Live Link update

### ISSUE THREAD

**Issue by divineniiquaye** [PiloeGAO/Blender-ArmorPaintLiveLink#3]
Hi @PiloeGAO the live link is very outdated without vectors color support and a 1 click import to blender, currently, it just exports the arm file.
Wud be very great if u cud update it 🙂

**Comment by PiloeGAO** [comment]
Hi @divineniiquaye,
What do you mean about vectors color? The color id inside of ArmorPaint?
I plan to bake vertex color inside of Blender to use it as color id in ArmorPaint but doing it by addon isn't the correct way (need to be done inside of the Blender Source Code).

With the latest update, you can use the 1 click import to get your textures correctly setup for EEVEE and Cycles (this feature need to setup a "project" folder).

Thank you for your feedback.
Bye!

**Comment by divineniiquaye** [comment]
Wait 🤗
Good job 👍
u rock!
