### ISSUE TITLE
Investigate moving to the @armory3d organization

### ISSUE THREAD

**Issue by Calinou** [PiloeGAO/Blender-ArmorPaintLiveLink#4]
I think it would make sense to migrate this addon (and its [Maya counterpart](https://github.com/PiloeGAO/Maya-ArmorPaintLiveLink)) to the @armory3d organization in the long term. This would ensure it can be maintained even if the original maintainers become unavailable in the future.

@luboslenco What do you think?

**Comment by PiloeGAO** [comment]
Hi @Calinou,
It's a really good suggestion !
I need to talk with @luboslenco about that.

**Comment by luboslenco** [comment]
Happy to host it directly in @armory3d if you are in @PiloeGAO. 🙂 Would of course also keep the full commit rights with you.

**Comment by Calinou** [comment]
Is this still relevant now? This repository is still under @PiloeGAO's account right now.
