### ISSUE TITLE
File not found when "Open into Armorpaint" on MacOS

### ISSUE THREAD

**Issue by max2198** [PiloeGAO/Blender-ArmorPaintLiveLink#5]
Hi, I have followed the installation guide but still have this message when clicking on "Open in Armor Paint"

MacOS 10.13.6
Blender 2.83.4
The latest offical Armorpaint Build

BTW it worked on my Windows PC

![3EC81FCD-7A24-44CF-A7B0-E9C676BBF6AF](https://user-images.githubusercontent.com/7226151/89720304-1f087500-d9d9-11ea-941c-52cb56fe2b89.jpg)

**Comment by PiloeGAO** [comment]
Hello,

Thanks for reporting this issue.
I will make a fix soon.

**Comment by ammein** [comment]
I have this issue too. Looking forward to the fix.
