### ISSUE TITLE
Open into ArmorPaint "Permission Error"

### ISSUE THREAD

**Issue by Somamint** [PiloeGAO/Blender-ArmorPaintLiveLink#7]
I installed the Plugin as requested. When i want to click now on " Open into ArmorPaint" i got this error:
https://postimg.cc/QBnbtz5p

**Comment by PiloeGAO** [comment]
Hello @Somamint,

This issue can be on two sides:
- You didn't setup the Armor Paint executable in the addon preferences.
- Your folder is locked/didn't exist.

Without further information, I can't give you what exactly produce this error.
Thank you

**Comment by Somamint** [comment]
First one, it works now!
