### ISSUE TITLE
Addon not working

### ISSUE THREAD

**Issue by JuroJino** [PiloeGAO/Blender-ArmorPaintLiveLink#8]
I've just downloaded the addon but Blender returns this error, how can i fix it? I'm using Blender 2.91 release. Thanks for your support. 
![image](https://user-images.githubusercontent.com/34395496/106818438-93fef380-6678-11eb-9e1f-4a06a83459bf.png)

**Comment by PiloeGAO** [comment]
Hello,
this is a path error, can you try to use a absolute path instead of relative for the ArmorPaint executable?
Thank you
