### ISSUE TITLE
Support of Blender 2.92 scheduled ?

### ISSUE THREAD

**Issue by French-VFR** [PiloeGAO/Blender-ArmorPaintLiveLink#9]
Hi,

Do you have planned to upgrade your plugin to be used with Blender 2.92 ?
Thanks for your stuff.

Lagaffe webmaster of http://frenchvfr.free.fr

**Comment by PiloeGAO** [comment]
Hello @French-VFR,

The addon is fully compatible with Blender 2.92.
![b3d_292](https://user-images.githubusercontent.com/43547972/109492559-76605680-7a8b-11eb-8793-9392fbec810e.jpg)

If you encounter any issues/bugs, please report them.

Thank you,
Léo
